- hosts: slurm-master
  roles:
    - {role: add-fbl-user, is_server: yes, user: "{{ user }}", password: "{{ password }}", new_user: new_user | default(false)}

- hosts: slurm-node
  roles:
    - {role: add-fbl-user, is_client: yes, user: "{{ user }}", password: "{{ password }}", new_user: new_user | default(false)}
