- name: Add unix user on client
  command: useradd -m -u "{{ user }}" -p `mkpasswd "{{ password }}"` -s /bin/bash -d "/home/{{ user }}" "{{ user }}"
  when: new_user | default(false)

- name: Modify unix user permissions on client
  command: usermod -aG "{{ ood_unix_group }}" "{{ user }}"
  when: new_user | default(false)

#- name: Configure SSH to allow new user
#  lineinfile:
#    path: /etc/ssh/sshd_config
#    line: "AllowUsers {{ user }}"
#    state: present
#    backup: yes

#- name: Restart ssh
#  systemd:
#    service: ssh
#    state: restarted

#- name: Restart sshd
#  systemd:
#    service: sshd
#    state: restarted

- name: Add FBL user directory
  file:
    path: "{{ fbl_directory }}/{{ user }}"
    state: directory
    mode: 0755
    owner: "{{ user }}"
  tags:
    - configure

- name: Copy singularity sandbox image into FBL user directory
  command: cp -r "{{ fbl_directory }}/fbl_image" "{{ fbl_directory }}/{{ user }}/fbl_image"

- name: Giving user ownership of the singularity sandbox image
  file:
    path: "{{ fbl_directory }}/{{ user }}/fbl_image"
    mode: 0755
    owner: "{{ user }}"
