- name: Add UNIX user
  command: useradd -m -u "{{ user }}" -p `mkpasswd "{{ password }}"` -s \bin\bash -d "/home/{{ user }}" "{{ user }}"
  when: new_user | default(false)

- name: Modify permissions for added UNIX user
  command: usermod -aG "{{ ood-unix-group }}" "{{ user }}"
  when: new_user | default(false)
  

- name: Set permissions for /home/NEWUSER
  command: chmod go-rwx "/home/{{ user }}"
  when: new_user | default(false)

- name: Configure ssh to allow NEWUSER
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "AllowUsers {{ user }}"
    state: present
    backup: yes 

- name: Restarting ssh
  systemd:
    service: ssh
    state: restarted

- name: Restarting sshd
  systemd:
    service: sshd
    state: restarted

- name: Add slurm user
  command: sacctmgr -i create user {{user}} account={{ood_slurm_account}} adminlevel=None
  register: create_user_result
  failed_when: "create_user_result.rc != 0 and 'Nothing new added' not in create_user_result.stdout"
  changed_when: "'Nothing new added' not in create_user_result.stdout"

- name: Add newuser to Open OnDemand
  command: htpasswd -b "{{ ood_passwd_file }}" "{{ user }}" "{{ password }}"

- name: Restarting Apache2 Server
  systemd:
    service: apache2
    state: restarted
