- hosts: slurm-master[0]
  become: yes
  roles:
    - {role: fbl-ood, is_server: yes, users: fbl-ood-users, use_cas: ood_use_cas}

- hosts:
  becomes: yes
  roles:
    - {role: fbl-ood, is_client: yes, users: fbl-ood-users, use_cas: ood_use_cas}
