- hosts: slurm-master[0]
  become: yes
  roles:
    - {role: fbl-ood, is_server: yes, main_user: ansible_user, use_cas: ood_use_cas}

- hosts: slurm-node
  becomes: yes
  roles:
    - {role: fbl-ood, is_client: yes, main_user: ansible_user, use_cas: ood_use_cas}
