---
- hosts: slurm-master[0]
  become: yes
  tasks:
    - name: Ensure /etc/apache2/ssl exists
      file:
        path: /etc/apache2/ssl
        state: directory
    - name: Transfer OOD SSL certificate file to slurm-master
      copy:
        src: "{{ ood_ssl_certificate }}"
        dest: /etc/apache2/ssl/ood-portal.crt
      when: ood_use_ssl | default(false)
    - name: Transfer OOD SSL certificate key file to slurm-master
      copy:
        src: "{{ ood_ssl_certificate_key }}"
        dest: /etc/apache2/ssl/ood-portal.key
      when: ood_use_ssl | default(false)

- hosts: slurm-master[0]
  become: yes
  roles:
    - {role: ood-wrapper, ood_is_server: yes, ood_use_ssl: ood_use_ssl}

- hosts: slurm-node
  become: yes
  roles:
    - {role: ood-wrapper, ood_is_client: yes }
