- name: Create FBL directory (under which fbl user directories are housed) on client
  file:
    path: "{{ fbl_directory }}"

#- name: Add main fbl user on client
#  roles:
#    - {role: add-fbl-user, is_client: yes, user: ansible_user, new_user: no}
