- debug:
    msg: is a client

- name: Create FBL directory (under which fbl user directories are housed) on client
  file:
    path: "{{ fbl_directory }}"
    state: directory

- name: Install python docker module
  pip:
    name: docker

- name: Pull FBL docker image from Docker Hub
  docker_image:
    name: fruitflybrain/fbl
    tag: slurm
    state: present
    source: pull

- name: Create FBL docker container
  command: docker create fruitflybrain/fbl:slurm /bin/bash --name fbl
  register: fbl_instance_id

- name: Copy FBL docker container contents into FBL directory
  command: docker cp "{{ fbl_instance_id.stdout }}:/" "{{ fbl_directory }}/fbl_image"

- name: Kill FBL docker container
  docker_container:
    name: fbl
    state: absent

#command: docker kill "{{ fbl_instance_id.stdout }}"

#- name: Remove FBL docker image
#  docker_image:
#    name: fruitflybrain/fbl
#    tag: slurm
#    state: absent
#    force_absent: yes
