- name: Create FBL directory (under which fbl user directories are housed) on client
  file:
    path: "{{ fbl_directory }}"

- name: Pull FBL docker image from Docker Hub
  docker_image:
    name: fruitflybrain/fbl
    tag: slurm
    state: present

- name: Create FBL docker container
  command: docker create fruitflybrain/fbl:slurm /bin/bash
  register: fbl_instance_id

- name: Copy FBL docker container contents into FBL directory
  command: docker cp "{{ fbl_instance_id }}:/" "{{ fbl_directory }}/fbl_image"

- name: Kill FBL docker container
  command: docker kill "{{ fbl_instance_id }}"

- name: Remove FBL docker image
  command: docker image rm fruitflybrain/fbl:slurm

- name: Add main fbl user on client
  include_role:
    name: add-fbl-user
  vars:
    is_client: yes
    is_server: no
    user: "{{ main_user }}"
    new_user: no
