- name: Clone FBL-OOD repository
  git:
       repo: https://github.com/jonmarty/FlyBrainLab-OOD
       dest: /home/ubuntu/fbl-ood
       clone: yes
       update: yes

- name: Copy OOD-APP into OOD apps directory
  command: cp -r /home/ubuntu/fbl-ood/ood-app /opt/ood/apps/.../fbl-ood

- name: Copy fbl-ood scripts to /bin
  command: cp /home/ubuntu/fbl-ood/bin/* /bin

- hosts: slurm-master[0]
  become: yes
  roles:
    - {role: add-fbl-user, is_server: yes, user: ansible_user, new_user: no}

- hosts: slurm-node
  becomes: yes
  roles:
    - {role: add-fbl-user, is_server: yes, user: ansible_user, new_user: no}
  
