- debug:
    msg: "is a server"

#- name: Clone FBL-OOD repository
#  git:
#       repo: https://github.com/jonmarty/FlyBrainLab-OOD
#       dest: /home/ubuntu/fbl-ood
#       clone: yes
#       update: yes

#- name: Copy OOD-APP into OOD apps directory
#  command: cp -r /home/ubuntu/fbl-ood/OOD-app /var/www/ood/apps/sys/fbl-ood

- name: Remove fbl app if it previously existed
  file:
    path: /var/www/ood/apps/sys/fbl/
    state: absent

- name: Add fbl app to ood
  copy:
       src: fbl
       dest: /var/www/ood/apps/sys/fbl

- name: Make sure before.sh.erb has the correct permissions
  file:
    path: /var/www/ood/apps/sys/fbl/template/before.sh.erb
    mode: "0744"

- name: Make sure after.sh.erb has the correct permissions
  file:
    path: /var/www/ood/apps/sys/fbl/template/after.sh.erb
    mode: "0744"

- name: Make sure script.sh.erb has the correct permissions
  file:
    path: /var/www/ood/apps/sys/fbl/template/script.sh.erb
    mode: "0744"

- name: Make sure libcuda.so.470.57.02 has the correct permissions
  file:
    path: /var/www/ood/apps/sys/fbl/template/libcuda.so.470.57.02
    mode: "0744"

#- name: Copy fbl-ood scripts to /bin
#  command: cp /home/ubuntu/fbl-ood/bin/* /bin

- name: Add ood slurm account
  command: sacctmgr -i add account "{{ood_slurm_account}}" Description="{{ood_slurm_account}}" Organization="{{ood_slurm_account}}"
  register: create_account_result
  failed_when: "create_account_result.rc != 0 and 'Nothing new added' not in create_account_result.stdout"
  changed_when: "'Nothing new added' not in create_account_result.stdout"
