- debug:
    msg: "is a server"

- name: Clone FBL-OOD repository
  git:
       repo: https://github.com/jonmarty/FlyBrainLab-OOD
       dest: /home/ubuntu/fbl-ood
       clone: yes
       update: yes

- name: Copy OOD-APP into OOD apps directory
  command: cp -r /home/ubuntu/fbl-ood/OOD-app /var/www/ood/apps/sys/fbl-ood

#- name: Copy fbl-ood scripts to /bin
#  command: cp /home/ubuntu/fbl-ood/bin/* /bin

- name: Add ood slurm account
  command: sacctmgr -i add account "{{ood_slurm_account}}" Description="{{ood_slurm_account}}" Organization="{{ood_slurm_account}}"
  register: create_account_result
  failed_when: "create_account_result.rc != 0 and 'Nothing new added' not in create_account_result.stdout"
  changed_when: "'Nothing new added' not in create_account_result.stdout"
  
- name: Add main fbl user on server
  include_role:
    name: add-fbl-user
  vars:
    is_server: yes
    is_client: no
    user: "{{ main_user }}"
    new_user: no
