- name: Clone FBL-OOD repository
  git:
       repo: https://github.com/jonmarty/FlyBrainLab-OOD
       dest: /home/ubuntu/fbl-ood
       clone: yes
       update: yes

- name: Copy OOD-APP into OOD apps directory
  command: cp -r /home/ubuntu/fbl-ood/OOD-app /var/www/ood/apps/sys/fbl-ood

#- name: Copy fbl-ood scripts to /bin
#  command: cp /home/ubuntu/fbl-ood/bin/* /bin

- name: Add ood slurm account
  command: sudo sacctmgr add account "{{ ood_slurm_account }}" "Description={{ ood_slurm_account }}" "Organization={{ ood_slurm_account}}"

- name: Add main fbl user on server
  include_role:
    name: add-fbl-user
  vars:
    is_server: yes
    user: ansible_user
    new_user: no
